name: Authentication Testing
on:
  push:
    branches:
      - main
      - users-auth-functionalities
  pull_request:
    branches:
      - main
jobs:
  auth-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.39
        env:
          MYSQL_ROOT_PASSWORD: qwerty21
          MYSQL_DATABASE: profismed_crm_db
        ports:
          - 3306:3306
    env:
      NODE_ENV: test
      DATABASE_URL: jdbc:mysql://149.130.164.6:3306/profismed_crm_db
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: actions/setup-node@v2
        with:
            node-version: '22'

      - name: Install dependencies
        run: npm install
